{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshell-driver-kyma.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshell-driver-kyma.labels" . | nindent 4 }}
{{- end }}
